from typing import Dict, Iterable, Iterator, Optional

def _initialize_global_thread_pool(num_threads: int) -> None: ...

class IntTypedList:
    # base 
    def __init__(self, data: Iterable[int]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __iter__(self) -> Iterator[int]: ...
    def __next__(self) -> int: ...
    def __contains__(self, value: int) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def append(self, value: int) -> None: ...
    def extend(self, values: Iterable[int]) -> None: ...

    # numeric
    def __add__(self, other: Iterable[int]) -> IntTypedList: ...
    def __add__(self, other: int) -> IntTypedList: ...
    def __sub__(self, other: Iterable[int]) -> IntTypedList: ...
    def __sub__(self, other: int) -> IntTypedList: ...
    def __mul__(self, other: Iterable[int]) -> IntTypedList: ...
    def __mul__(self, other: int) -> IntTypedList: ...
    def __truediv__(self, other: Iterable[int]) -> IntTypedList: ...
    def __truediv__(self, other: int) -> IntTypedList: ...

    # sort 
    def sort(self) -> None: ...
    
    # hash
    def unique(self) -> IntTypedList: ...
    def count(self) -> Dict[int, int]: ...

class FloatTypedList:
    def __init__(self, data: Iterable[float]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __next__(self) -> float: ...
    def __contains__(self, value: float) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def append(self, value: float) -> None: ...
    def extend(self, values: Iterable[float]) -> None: ...

    # numeric
    def __add__(self, other: Iterable[float]) -> FloatTypedList: ...
    def __add__(self, other: float) -> FloatTypedList: ...
    def __sub__(self, other: Iterable[float]) -> FloatTypedList: ...
    def __sub__(self, other: float) -> FloatTypedList: ...
    def __mul__(self, other: Iterable[float]) -> FloatTypedList: ...
    def __mul__(self, other: float) -> FloatTypedList: ...
    def __truediv__(self, other: Iterable[float]) -> FloatTypedList: ...
    def __truediv__(self, other: float) -> FloatTypedList: ...

    # sort
    def sort(self) -> None: ...

class StringTypedList:
    def __init__(self, data: Iterable[str]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> str: ...
    def __setitem__(self, index: int, value: str) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __next__(self) -> str: ...
    def __contains__(self, value: str) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def append(self, value: str) -> None: ...
    def extend(self, values: Iterable[str]) -> None: ...

    # sort
    def sort(self) -> None: ...

    # hash
    def unique(self) -> StringTypedList: ...
    def count(self) -> Dict[str, int]: ...
