from typing import Iterable

def _initialize_global_thread_pool(num_threads: int) -> None: ...

class IntTypedList:
    def __init__(self, data: Iterable[int]) -> None: ...

class FloatTypedList:
    def __init__(self, data: Iterable[float]) -> None: ...

class StringTypedList:
    def __init__(self, data: Iterable[str]) -> None: ...

class BoolTypedList:
    def __init__(self, data: Iterable[bool]) -> None: ...
